basePath: /
definitions:
  github_com_francotraversa_Sliceflow_internal_types.ProductCreateRequest:
    properties:
      Quantity:
        example: 10
        type: integer
      description:
        example: Importación Diciembre
        type: string
      name:
        example: PLA PRINT A LOT 1KG AZUL
        type: string
      price:
        example: 98.5
        type: number
      sku:
        example: "7791234567890"
        type: string
        x-order: "1"
    type: object
  github_com_francotraversa_Sliceflow_internal_types.ProductUpdateRequest:
    properties:
      description:
        example: Importación Diciembre
        type: string
      name:
        example: PLA PRINT A LOT 1KG AZUL
        type: string
      price:
        example: 98.5
        type: number
      quantity:
        example: 10
        type: integer
      sku:
        example: "7791234567890"
        type: string
        x-order: "1"
    type: object
  github_com_francotraversa_Sliceflow_internal_types.StockItem:
    properties:
      created_at:
        type: string
      description:
        type: string
      min_qty:
        type: number
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      sku:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  github_com_francotraversa_Sliceflow_internal_types.TokenResponse:
    properties:
      expires:
        type: integer
      token:
        type: string
    type: object
  github_com_francotraversa_Sliceflow_internal_types.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      password:
        description: hash
        type: string
      role:
        type: string
      status:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  github_com_francotraversa_Sliceflow_internal_types.UserCreateCreds:
    properties:
      password:
        example: usertest
        type: string
      role:
        example: user
        type: string
      username:
        example: usertest
        type: string
    type: object
  github_com_francotraversa_Sliceflow_internal_types.UserLoginCreds:
    properties:
      password:
        example: hornero3dx
        type: string
      username:
        example: hornero3dx
        type: string
    type: object
  github_com_francotraversa_Sliceflow_internal_types.UserUpdateCreds:
    properties:
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8181
info:
  contact: {}
  description: Documentación de mi API con Echo.
  title: API de Sliceflow
  version: "1.0"
paths:
  /health:
    get:
      description: Devuelve OK si el servicio está arriba
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Chequear estado
      tags:
      - Health
  /hornero/auth/login:
    post:
      consumes:
      - application/json
      description: Autentica al usuario y devuelve un token JWT
      parameters:
      - description: Credenciales
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.UserLoginCreds'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.TokenResponse'
      summary: Iniciar sesión
      tags:
      - Authenticator
  /hornero/loged/admin/alluser:
    get:
      description: Obtiene una lista de usuarios filtrada por rol o estado. Solo accesible
        para ADMIN.
      parameters:
      - description: Filtrar por rol (admin/user)
        in: query
        name: role
        type: string
      - description: Filtrar por estado (active/disabled)
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.User'
            type: array
        "400":
          description: Error en la solicitud
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Listar todos los usuarios
      tags:
      - Users
  /hornero/loged/admin/deleteuser/{id}:
    delete:
      description: Cambia el estado del usuario a 'disabled'. Requiere ser el dueño
        de la cuenta o ADMIN.
      parameters:
      - description: ID del usuario a borrar (solo para Admins)
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: The UserID [id] has been deleted
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Borrado lógico de usuario
      tags:
      - Users
  /hornero/loged/admin/edituser/{id}:
    patch:
      consumes:
      - application/json
      description: Actualiza datos de un usuario. Si se pasa ID en la URL, requiere
        ser ADMIN. Si no, actualiza al usuario del token.
      parameters:
      - description: ID del usuario a editar (solo para Admins)
        in: path
        name: id
        type: integer
      - description: Datos a actualizar
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.UserUpdateCreds'
      produces:
      - application/json
      responses:
        "200":
          description: The User ID [id] has been updated
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Actualizar usuario
      tags:
      - Users
  /hornero/loged/admin/newuser:
    post:
      consumes:
      - application/json
      description: Crea un usuario en la base de datos. Requiere rol de ADMIN.
      parameters:
      - description: Credenciales del usuario
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.UserCreateCreds'
      produces:
      - application/json
      responses:
        "200":
          description: The User [username] has been created
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Registrar un nuevo usuario
      tags:
      - Users
  /hornero/loged/deletemyuser:
    delete:
      description: Cambia el estado del usuario a 'disabled'. Requiere ser el dueño
        de la cuenta o ADMIN.
      produces:
      - application/json
      responses:
        "200":
          description: The UserID [id] has been deleted
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Borrado lógico de usuario
      tags:
      - Users
  /hornero/loged/stock/{sku}:
    delete:
      description: Realiza un soft-delete del producto usando su ID.
      parameters:
      - description: ID del producto
        in: path
        name: sku
        required: true
        type: integer
      responses:
        "200":
          description: The Product has been deleted
          schema:
            type: string
        "400":
          description: ID inválido
          schema:
            type: string
        "409":
          description: Error al eliminar
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Baja lógica de producto
      tags:
      - Stock
    get:
      description: Busca un producto específico usando su ID numérico de base de datos.
      parameters:
      - description: ID del producto
        in: path
        name: sku
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.StockItem'
        "400":
          description: ID inválido
          schema:
            type: string
        "409":
          description: Producto no encontrado
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Obtener producto por ID
      tags:
      - Stock
    put:
      consumes:
      - application/json
      description: Edita nombre, descripción, status o stock mínimo de un producto
        existente.
      parameters:
      - description: ID del producto
        in: path
        name: sku
        required: true
        type: integer
      - description: Datos a actualizar
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.ProductUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated successfully
          schema:
            type: string
        "400":
          description: Error de validación o ID inválido
          schema:
            type: string
        "404":
          description: Producto no encontrado
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Actualizar datos de un producto
      tags:
      - Stock
  /hornero/loged/stock/list:
    get:
      description: Obtiene la lista completa de productos en stock que no han sido
        borrados.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.StockItem'
            type: array
        "409":
          description: Error al obtener productos
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Listar todos los productos
      tags:
      - Stock
  /hornero/loged/stock/product:
    post:
      consumes:
      - application/json
      description: Registra un producto en el catálogo usando el SKU (código de barras)
        y nombre.
      parameters:
      - description: Datos del producto a crear
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product has been created
          schema:
            type: string
        "400":
          description: Invalid Json o error de validación
          schema:
            type: string
        "409":
          description: El SKU ya existe
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Crear un nuevo producto
      tags:
      - Stock
  /hornero/loged/updmyuser:
    patch:
      consumes:
      - application/json
      description: Actualiza datos de un usuario. Si se pasa ID en la URL, requiere
        ser ADMIN. Si no, actualiza al usuario del token.
      parameters:
      - description: Datos a actualizar
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_francotraversa_Sliceflow_internal_types.UserUpdateCreds'
      produces:
      - application/json
      responses:
        "200":
          description: The User ID [id] has been updated
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Actualizar usuario
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    description: 'Escribí "Bearer " seguido de tu token JWT. Ejemplo: "Bearer eyJhbG..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
